### ISSUE TITLE
Brilliant script but have small problem

### ISSUE THREAD

**Issue by Yippeekiyay420** [PineappleOnMyPizza/qb-towrequest#2]
Hey love the script however we moved to a new phone. qs-smartphone and I am unable to use the script with the phone. could you add support for that?

**Comment by MajiSP** [comment]
I will never add support for anything quasar related. They are thieves, provide little to no support for paying customers, and have no idea how to properly develop things with present day practice.

**Comment by Yippeekiyay420** [comment]
I agree tbh we paid a fortune and the service is poor. We have decided to revert back to a renewed phone in our city
